blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('blog/create', BlogCreateView.as_view(), name='blog_create'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/<int:pk>/update', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<int:pk>/delete', BlogDeleteView.as_view(), name='blog_delete')

]

catalog/urls.py
from django.urls import path
from . import views
from .views import ProductCreateView

app_name = 'catalog'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('contacts/', views.ContactsView.as_view(), name='contacts'),
    path('products/', views.ProductsListView.as_view(), name='products_list'),
    path('products/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('product_create/', ProductCreateView.as_view(), name='product_create'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth import login
from django.urls import path
from .views import RegisterView
from django.contrib.auth.views import LoginView,LogoutView

app_name = 'users'

urlpatterns = [
    path ('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path ('logout/', LogoutView.as_view(), name='logout'),
]

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Содержимое')
    image = models.ImageField(upload_to='blog/image', blank=True, null=True, verbose_name='Изображение')
    created_at = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    publication = models.BooleanField(default=True, verbose_name='публикация')
    number_views = models.PositiveIntegerField(verbose_name="Количество просмотров",
                                               help_text="Укажите количество просмотров", default=0)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'

blog/views.py
from django.urls import reverse_lazy, reverse
from .models import Blog
from django.views.generic import DetailView, ListView, CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin


class BlogListView(ListView):
    model = Blog

    def get_queryset(self):
        # Получаем только активные объекты
        return Blog.objects.filter(publication=True)


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    fields = ("title", "content", "image", )
    success_url = reverse_lazy("blog:blog_list")


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ("title", "content", "image")
    success_url = reverse_lazy("blog:blog_list")

    def get_success_url(self):
        return reverse('blog:blog_detail', args=[self.kwargs.get('pk')])


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.number_views += 1
        self.object.save()
        return self.object


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy("blog:blog_list")

blog/templates/blog/base.html
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}<Блог>{% endblock %}</title>
    <!-- Подключение Bootstrap CSS -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Блог</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'catalog:products_list' %}">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Посты</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Редактировать пост</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Добавить Пост</a>
                </li>


                {% if user.is_authenticated %}
                     <li class="nav-item">
                          <form method="post" action="{% url 'users:logout' %}" style="display:inline">
                              {% csrf_token %}
                              <button type="submit" class="btn btn-link nav-link ">Выйти</button>

                          </form>
                </li>

                {% else %}
                 <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
                </li>
                 <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>

                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container mt-5">
        {% block content %}{% endblock %}
    </div>
    <!-- Подключение Bootstrap JS -->
    <script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

blog/templates/blog/blog_confirm_delete.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <p class="card-text text-center">Вы уверенны?</p>
                    <div class="card-body">
                        {% csrf_token %}
                    </div>
                    <div class="d-grid gap-2 col-4 mx-auto">
                        <button type="submit" class="btn btn-danger ">Удалить</button>
                        <a class="btn btn-primary" href="{% url 'blog:blog_list' %}" role="button">Отмена</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'blog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Категории</h1>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.title}}</h4>
                </div>
                <div class="card-body">
                    <h2 class="card-title pricing-card-title">{{ object.content}}</h2>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3"></ul>
                     <img class="img-responsive" width="300" src="{{ blog.image | filter_media  }}">
                    <div class="btn-group">
                        <a class="btn btn-primary" href="{% url 'blog:blog_list' %}" role="button">Назад</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="container">
    <div class="row ">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {%  endif %}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'blog/base.html' %}
{% load my_tags %}
{% block content %}
   <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">НЕ ИНСТАГРАМ</h1>
</div>

<div class="container">
    <div class="row text-center">
        {% for blog in object_list %}
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ blog.title}}</h4>
                </div>
                <div class="card-body">
                    <h2 class="card-title pricing-card-title">Описание</h2>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li class="text-center">{{ blog.content|truncatechars:100}}</li>
                    </ul>
                   <img class="img-responsive" width="300" src="{{ blog.image | filter_media  }}">
                    <div class="btn-group">
                        <a class="btn btn-primary" href="{% url 'blog:blog_detail' blog.pk %}" role="button">Перейти</a>
                        <a class="btn btn-primary" href="{% url 'blog:blog_update' blog.pk %}" role="button">Редактировать</a>
                        <a class="btn btn-danger" href="{% url 'blog:blog_delete' blog.pk %}" role="button">Удалить</a>
                    </div>
                    <h4 class="card-title pricing-card-title">Количество просмотров: {{ blog.number_views }}</h4>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>
</div>
<div class="row text-center">
    <div class="col-12 ">
                <a class="btn btn-primary" href="{% url 'blog:blog_create' %}" role="button">Создать новый блог</a>
    </div>
</div>
{% endblock %}