blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('blog/create', BlogCreateView.as_view(), name='blog_create'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/<int:pk>/update', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<int:pk>/delete', BlogDeleteView.as_view(), name='blog_delete')

]

catalog/urls.py
from django.urls import path
from . import views
from .views import ProductCreateView

app_name = 'catalog'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('contacts/', views.ContactsView.as_view(), name='contacts'),
    path('products/', views.ProductsListView.as_view(), name='products_list'),
    path('products/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('product_create/', ProductCreateView.as_view(), name='product_create'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth import login
from django.urls import path
from .views import RegisterView
from django.contrib.auth.views import LoginView,LogoutView

app_name = 'users'

urlpatterns = [
    path ('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path ('logout/', LogoutView.as_view(), name='logout'),
]

catalog/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(
        max_length=100, verbose_name="Наименование категории", help_text="Введите наименование категории"
    )
    description = models.TextField(
        verbose_name="Описание категории", help_text="Введите описание категории", blank=True, null=True
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"
        ordering = ["name"]


class Product(models.Model):
    name = models.CharField(
        max_length=100, verbose_name="Наименование продукта", help_text="Введите наименование продукта"
    )
    description = models.TextField(
        verbose_name="Описание продукта", help_text="Введите описание продукта", blank=True, null=True
    )
    image = models.ImageField(upload_to="catalog/image", blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, related_name="products", blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, help_text="Введите цену за покупку")
    created_at = models.DateField(verbose_name="Дата создания", blank=True, null=True)
    updated_at = models.DateField(verbose_name="Дата последнего изменения", blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "продукт"
        verbose_name_plural = "продукты"
        ordering = ["category", "name", "price"]

catalog/forms.py
from django import forms
from .models import Product, Category
from django.core.exceptions import ValidationError

forbidden = ['казино', 'криптовалюта', 'крипта', 'биржа',
             'дешево', 'бесплатно', 'обман', 'полиция', 'радар']


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'image', 'category', 'price', 'created_at']

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите имя'
        })
        self.fields['description'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Введите описание'})
        self.fields['image'].widget.attrs.update({'class': 'form-control'})
        self.fields['category'].widget.attrs.update({'class': 'form-control'})
        self.fields['price'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Введите цену'})
        self.fields['created_at'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Введите дату'})

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if any(word in name.lower() for word in forbidden):
            raise ValidationError("Название не должно содержать запрещенные слова.")
        return name

    def clean_description(self):
        description = self.cleaned_data.get('description')
        if any(word in description.lower() for word in forbidden):
            raise ValidationError("Название не должно содержать запрещенные слова.")
        return description

    def clean_price(self):
        price = self.cleaned_data.get('price')
        if price < 0:
            raise ValidationError("Неверная цена")
        return price


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'description']


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, forms.BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'

catalog/views.py
from itertools import product

from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from catalog.forms import ProductForm
from catalog.models import Product

''
class HomeView(TemplateView):
    template_name = 'catalog/products_list.html'


class ContactsView(TemplateView):
    template_name = 'catalog/contacts.html'


class ProductsListView(TemplateView):
    template_name = 'catalog/products_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = Product.objects.all()
        context['products'] = products
        return context


class ProductDetailView(TemplateView):
    template_name = 'catalog/product_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get('pk')
        product = get_object_or_404(Product, pk=pk)
        context['product'] = product
        return context

class ProductCreateView(LoginRequiredMixin,CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'catalog/product_form.html'
    success_url = reverse_lazy('catalog:home')

catalog/templates/catalog/base.html
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}<Блог>{% endblock %}</title>
    <!-- Подключение Bootstrap CSS -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Магазин</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'catalog:products_list' %}">Товары</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'catalog:product_create' %}">Добавить товар</a>
                </li>

                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:blog_list' %}">Блог</a>
                </li>


                {% if user.is_authenticated %}

                     <li class="nav-item">
                          <form method="post" action="{% url 'users:logout' %}" style="display:inline">
                              {% csrf_token %}
                              <button type="submit" class="btn btn-link nav-link ">Выйти</button>

                          </form>
                </li>

                {% else %}
                 <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
                </li>
                 <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>

                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container mt-5">
        {% block content %}{% endblock %}
    </div>
    <!-- Подключение Bootstrap JS -->
    <script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
{% include 'catalog/header.html' %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Контакты</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:products_list' %}">Главная</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:home' %}">О нас</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>
{% endblock %}

catalog/templates/catalog/header.html
<header>
    <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Магазин</h1>
        <p class="lead text-body-secondary">Здесь есть все.</p>
      </div>
    </div>
  </section>
</header>

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
{% include 'catalog/header.html' %}
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
        <h5 class="my-0 mr-md-auto font-weight-normal">О нас</h5>
        <nav class="ms-5">
            <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:products_list' %}">Главная</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
        </nav>
    </div>
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Добро пожаловать на наш сайт!</h1>
    </div>
    <script src="/static/js/bootstrap.bundle.min.js"></script>

{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
{% include 'catalog/header.html' %}
<div class="album py-5 bg-body-tertiary">
<div class="container">
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    <div class="col">
      <div class="card shadow-sm">
        <img src="{{ product.image | filter_media }}">
        <div class="card-body">
          <p class="card-text">{{ product.category }}</p>
          <p class="card-text">{{ product.name }}</p>
          <p>{{ product.description }}</p>
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
              <a class="btn btn-primary" href="{% url 'catalog:products_list' %}" role="button">Назад</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/home.html'%}
{% load my_tags %}
{% include 'catalog/includes/inc_menu.html'%}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container mt-5">
        <h1 class="mb-4">Добавить новый продукт </h1>
        <form method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
                <a class="btn btn-primary" href="{% url 'catalog:home' %}">Назад</a>
        </form>
    </div>
    <script src="/static/js/bootstrap.bundle.min.js"></script>
{% endblock %}
{% include 'catalog/includes/footer.html'%}

catalog/templates/catalog/product_list.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
{% include 'header.html' %}
<nav class="ms-5">
    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:home' %}">О нас</a>
</nav>
<div class="album py-5 bg-body-tertiary">
  <div class="container">
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for product in products %}
    <div class="col">
      <div class="card shadow-sm">
        <img src="{{ product.image | filter_media }}">
        <div class="card-body">
          <p class="card-text">{{ product.name }}</p>
          <p>{{ product.description|truncatechars:100 }}</p>
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
              <a class="btn btn-primary" href="{% url 'catalog:product_detail' product.pk %}" role="button">Подробнее</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  </div>
</div>
{% endblock %}

catalog/templates/catalog/products_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
{% include 'catalog/header.html' %}
<nav class="ms-5">
    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:home' %}">О нас</a>
</nav>
<div class="album py-5 bg-body-tertiary">
  <div class="container">
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for product in products %}
    <div class="col">
      <div class="card shadow-sm">
        <img src="{{ product.image | filter_media }}">
        <div class="card-body">
          <p class="card-text">{{ product.name }}</p>
          <p>{{ product.description|truncatechars:100 }}</p>
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
              <a class="btn btn-primary" href="{% url 'catalog:product_detail' product.pk %}" role="button">Подробнее</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  </div>
</div>
{% endblock %}